version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Get and install node version manager.
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - run:
          name: Install Node version 12 using NVM
          command: nvm install 12 
      - run:
          name: Use Node version 12 
          command: nvm use 12     
      - run:
          name: Front-End Install
          command: |
            cd ./udagram-frontend && npm install
      - run:
          name: Back-End Install
          command: |
            cd ./udagram-api && npm install
      - run:
          name: Front-End Build
          command: |
            cd ./udagram-frontend && npm run build
      - run:
          name: Back-End Build
          command: |
            cd ./udagram-api && npm run build
      - run:
          name: Deploy App
          command: |
            cd ./udagram-frontend && npm run deploy
