version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
          node-version: "14.15"
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            cd ./udagram-frontend && npm install
      - run:
          name: Back-End Install
          command: |
            cd ./udagram-api && npm install
      - run:
          name: Front-End Build
          command: |
            cd ./udagram-frontend && npm run build
      - run:
          name: Back-End Build
          command: |
            cd ./udagram-api && npm run build
      - run:
          name: Deploy App
          command: |
            cd ./udagram-frontend && npm run deploy
      - run:
          name: Deploy Backend
          command: |
            cd ./udagram-api && npm run deploy
